 "secret-leak": ("A02", "CRITICAL", "Secret or live API key shipped to the browser",
   "any visitor can read the key and spend your money or your data",
   "pull the key out of the client bundle at once, rotate it, issue a scoped server-side replacement, restrict the old key"),
 "host-header": ("A07", "MEDIUM", "Untrusted Host/X-Forwarded-Host reaches output",
   "password-reset and absolute links can be poisoned to attacker infrastructure",
   "build URLs from a configured canonical origin, never from request headers; reject unknown Host values at the proxy"),
 "graphql-introspection": ("A02", "MEDIUM", "GraphQL introspection enabled in production",
   "the full schema, including hidden mutations, is enumerable by anyone",
   "disable introspection in production (Apollo: introspection: false; Hasura/GraphQL Yoga: disable for anon roles)"),
 "cookie-samesite-none": ("A07", "MEDIUM", "SameSite=None cookie without Secure",
   "browsers reject or degrade the cookie and cross-site leaks widen",
   "set Secure alongside SameSite=None, or switch to SameSite=Lax"),
 "exp-api-docs": ("A02", "MEDIUM", "API documentation exposed publicly",
   "the full API surface, including forgotten endpoints, is handed to attackers",
   "serve OpenAPI/Swagger only in staging or behind auth; block schema paths at the edge"),
 "exp-admin-panel": ("A02", "HIGH", "Admin interface reachable from the internet",
   "database or server admin panels are brute-force and 0-day targets",
   "bind admin panels to localhost or a VPN, add IP allowlisting plus MFA, remove them from public DNS"),
 "subdomain-dangling": ("A02", "LOW", "Certificate-log subdomain no longer resolves",
   "a dangling name can be re-claimed and turned into subdomain takeover",
   "delete the stale DNS record or claim the external resource, then re-check the name"),
 "jwt-alg-none": ("A07", "HIGH", "JWT issued with alg=none",
   "anyone can mint a valid token for any user, full account takeover",
   "reject alg none and pin an allowlist (e.g. RS256) in the verifier, validate signature before claims"),
 "jwt-weak-secret": ("A04", "CRITICAL", "JWT signed with a guessable secret",
   "attackers forge tokens offline, no login needed",
   "switch to RS256/ES256 or a 256-bit random secret, store it in a secret manager, rotate it"),
 "jwt-no-exp": ("A07", "MEDIUM", "JWT has no expiration claim",
   "tokens live forever, logout and password change do not revoke them",
   "set short exp (minutes to hours), validate exp/nbf/iss/aud, back long sessions with refresh tokens"),
 "jwt-long-life": ("A07", "LOW", "JWT expiration is very long",
   "a leaked token stays useful for a very long window",
   "shorten access-token lifetime to under an hour, use refresh rotation"),
 "exp-git": ("A02", "HIGH", "Git repository exposed on the server",
   "the full source tree and history ship to the attacker, secrets inside get harvested",
   "remove .git from deployment artifacts, deny dotfiles at the server: location ~ /\\.git { deny all; }"),
 "exp-env": ("A02", "CRITICAL", "Environment file exposed",
   "API keys, DB passwords and tokens are handed over in one request",
   "move .env outside the web root, deny dotfiles, then rotate EVERY secret it ever contained"),
 "exp-backup": ("A02", "HIGH", "Backup or archive file exposed",
   "source code, databases or keys leak through leftover deploy files",
   "delete backups from the web root, store them outside docroot, deny *.bak *.old *.zip *.sql *.tar.gz"),
 "exp-config": ("A02", "MEDIUM", "Configuration file exposed",
   "internal paths, credentials or feature flags become known",
   "block config filenames at the server and stop shipping them in builds"),
 "exp-deps": ("A03", "LOW", "Dependency manifest exposed",
   "exact component versions are known, CVE matching becomes one-shot",
   "deny package manifests at the edge; run npm audit / osv-scanner to check those versions yourself first"),
 "exp-aws": ("A02", "CRITICAL", "Cloud credentials file exposed",
   "your cloud account is directly compromiseable",
   "remove the file, rotate those credentials immediately, use an instance role instead of keys on disk"),
 "exp-keyfile": ("A04", "CRITICAL", "Private key file exposed on the server",
   "attackers decrypt recorded traffic or impersonate your services",
   "remove the key from the web root immediately and rotate it (reissue the certificate / API key), store keys outside docroot"),
 "exp-debug-endpoint": ("A02", "MEDIUM", "Debug/monitoring endpoint exposed",
   "runtime config, env values and internal state are disclosed",
   "disable actuator/phpinfo/server-status style endpoints in production, bind them to localhost or auth"),
 "exp-sourcemap": ("A08", "MEDIUM", "Source map published",
   "original source (including comments and internal APIs) is recoverable",
   "strip sourceMappingURL from shipped JS or serve .map files only for internal builds"),
 "dir-listing": ("A02", "MEDIUM", "Directory listing enabled",
   "attackers enumerate backups, uploads and forgotten files",
   "autoindex off; (nginx) / Options -Indexes (Apache)"),
 "err-stacktrace": ("A10", "HIGH", "Stack trace or debug page exposed",
   "internal paths, framework versions and query shapes leak, aiding follow-up attacks",
   "return generic errors with a correlation ID, keep traces in protected logs, disable debug mode in production"),
 "xss-reflected": ("A05", "HIGH", "Reflected cross-site scripting",
   "attacker links hijack any victim's session on your domain",
   "context-aware output encoding (framework auto-escape), avoid innerHTML, add CSP as a second layer"),
 "sqli-error": ("A05", "HIGH", "SQL injection (database error revealed)",
   "the query is attacker-influenced; data theft or modification may follow",
   "use parameterized prepared statements for every value, allowlist identifiers, least-privilege DB account"),
 "sqli-boolean": ("A05", "MEDIUM", "Possible SQL injection (boolean differential)",
   "attacker can walk the database one boolean at a time",
   "same fix as error-based SQLi: parameterized queries everywhere"),
 "cmdi-echo": ("A05", "CRITICAL", "OS command injection",
   "the attacker runs arbitrary commands on your server, total compromise",
   "never pass input to a shell; call fixed executables with argument arrays, allowlist inputs"),
 "traversal": ("A05", "HIGH", "Path traversal",
   "arbitrary file read: configs, keys, source",
   "canonicalize and verify the resolved path stays under the allowed base dir, allowlist filenames"),
 "redirect-open": ("A06", "MEDIUM", "Open redirect",
   "phishing links borrow your trusted domain",
   "allowlist redirect targets (path-only or known hosts), reject scheme-relative and absolute URLs"),
 "admin-force-browse": ("A01", "HIGH", "Admin surface reachable without login",
   "anyone can reach privileged pages and APIs",
   "deny by default: authenticate every route, then authorize by role, server-side"),
 "csrf-token-missing": ("A01", "MEDIUM", "State-changing form without CSRF token",
   "a third-party page can submit this form with the victim logged in",
   "add a per-session CSRF token (constant-time compare) and SameSite cookies; never rely on secrecy of URLs"),
 "ratelimit-login": ("A07", "LOW", "No rate limit observed on login",
   "credential stuffing and password spraying run at scale",
   "layer limits (edge + app): e.g. 4/min then 10/10min then 20/hour per IP+account, count failures, add CAPTCHA"),
 "sri-missing": ("A08", "LOW", "Third-party script without Subresource Integrity",
   "a compromised CDN silently runs attacker code in your pages",
   "add integrity=\"sha384-...\" and crossorigin to every cross-origin script/link, or self-host the asset"),
 "mixed-content": ("A04", "MEDIUM", "Mixed content on an HTTPS page",
   "plain-HTTP subresources are readable and tamperable in transit",
   "reference all subresources over HTTPS and add upgrade-insecure-requests to CSP"),
 "method-trace": ("A02", "MEDIUM", "HTTP TRACE enabled",
   "cross-site tracing can echo custom headers back to scripts",
   "disable TRACE at the server/proxy: nginx does not enable it by default, apache: TraceEnable off"),
 "method-put": ("A02", "MEDIUM", "Write methods accepted (PUT/DELETE)",
   "unauthenticated file upload or deletion may be possible",
   "reject non-GET/POST at the edge, require auth and CSRF on any allowed write method"),
 "sec-txt-missing": ("RFC 9116", "INFO", "security.txt missing",
   "researchers have no documented channel to report issues to you",
   "publish /.well-known/security.txt with Contact: mailto:you@domain and Policy: link"),
 "robots-disclosure": ("A02", "LOW", "robots.txt reveals sensitive paths",
   "disallowed admin/backup paths are published to everyone",
   "remove secret paths from robots.txt, block them at the server instead"),
 "global-secret-sweep": ("A02", "HIGH", "Secret or trace signature in served content",
   "a key or an internal trace that no single check looked for is readable by anyone",
   "pull the value out of client-visible content, rotate it at the provider and keep it server-side; return generic error pages and store traces in private logs"),
"desync-confirmed": ("A01", "CRITICAL",
    "Confirmed HTTP request desync cross-contamination (CWE-444)",
    "one client's request is answered with another client's request or "
    "response: sessions, responses and cache entries cross over between users",
    "end to end HTTP/2 or a single strict HTTP/1.1 parser, reject duplicate "
    "Content-Length and Transfer-Encoding, and validate rewritten requests "
    "against RFC 9112 before forwarding"),
  "desync-cells": ("A06", "INFO", "Length-interpretation cell (CL/TE/0/H2) probe",
    "an anomaly, not a vulnerability: one hop read a different message length "
    "than another hop did",
    "read the anomaly table and confirm by hand before changing anything; a "
    "differential here is a lead, not a bug"),
  "unicode-oracle": ("A07", "INFO",
    "Unicode normalization oracle in a reflected value",
    "an anomaly, not a vulnerability: the stored or echoed form of a value "
    "differs from the form sent, which can break an identity comparison",
    "normalize with NFKC on input and on the stored value, compare code-point "
    "sequences rather than rendered strings, reject mixed-form input at the edge"),
  "delimiter-confusion": ("A02", "INFO",
    "Path delimiter handled differently by cache and origin",
    "an anomaly, not a vulnerability: two hops disagree about what the path "
    "is, which is the precondition for cache poisoning",
    "normalize the path once at the edge, cache only on the normalized key, "
    "reject unencoded ; . and %2e upstream"),
  "api-state-authz": ("A01", "INFO",
    "Authorization differential on a documented object path",
    "an anomaly, not a vulnerability: an unauthenticated read of a single "
    "object differs from the anonymous collection baseline",
    "authenticate then authorize per object server-side; add a second "
    "owner-provided test account to the plan and re-run before concluding "
    "anything about BOLA"),
}

GROUPS = {
 "recon": ["sec-txt-missing", "robots-disclosure", "hdr-banner"],
 "tls": ["no-tls", "tls-legacy", "tls-expiry", "tls-unverified"],
 "headers": ["hdr-hsts", "hdr-csp-missing", "hdr-csp-unsafe", "hdr-nosniff",
   "hdr-referrer", "hdr-permissions", "hdr-xss-legacy", "hdr-obsolete",
   "hdr-coop", "hdr-corp", "hdr-x-powered", "hdr-cache-sensitive", "clickjack"],
 "cors": ["cors-reflect", "cors-null", "cors-star"],
 "cookies": ["cookie-secure", "cookie-httponly", "cookie-samesite",
   "cookie-samesite-none", "cookie-plaintext", "cookie-long-life"],
 "jwt": ["jwt-alg-none", "jwt-weak-secret", "jwt-no-exp", "jwt-long-life"],
 "secrets": ["secret-leak"],
 "exposures": ["exp-git", "exp-env", "exp-backup", "exp-config", "exp-deps",
   "exp-aws", "exp-keyfile", "exp-api-docs", "exp-admin-panel",
   "exp-debug-endpoint", "exp-sourcemap",
   "dir-listing", "err-stacktrace", "graphql-introspection"],
 "injection": ["xss-reflected", "sqli-error", "sqli-boolean", "cmdi-echo",
   "traversal", "redirect-open"],
 "auth": ["admin-force-browse", "csrf-token-missing", "ratelimit-login",
   "host-header", "subdomain-dangling"],
 "client": ["sri-missing", "mixed-content"],
 "methods": ["method-trace", "method-put"],
 "sweep": ["global-secret-sweep"],
}
SCENARIOS = {
 "recon": ["recon"],
 "headers": ["tls", "headers", "cors", "cookies"],
 "misconfig": ["exposures", "methods"],
 "injection": ["injection"],
 "auth": ["auth", "jwt"],
 # the whole-corpus sweep runs after exposures, so it sees the files the
 # exposure probes captured and not only the crawl
 "full": ["recon", "tls", "headers", "cors", "cookies", "jwt", "secrets",
   "exposures", "sweep", "injection", "auth", "client", "methods"],
 "anomaly": ["anomaly"],
 "tierc": ["tierc"],
"tierb": ["desync-confirmed", "desync-cells", "unicode-oracle",
   "delimiter-confusion", "api-state-authz"],
 "api": ["recon", "exposures", "cors", "injection"],
# the API state walk reads the OpenAPI document that exp-api-docs captured,
# so the exposures group has to run first inside the tierb scenario
"tierb": ["exposures", "tierb"],
}
