
# check_id -> (owasp, default_severity, title, attacker win, exact fix)
CHECKS = {
 "no-tls": ("A04", "HIGH", "Site served over plain HTTP",
   "an attacker on the same network reads and edits every request",
   "redirect all HTTP to HTTPS and serve only TLS 1.2+, e.g. nginx: return 301 https://$host$request_uri;"),
 "tls-legacy": ("A04", "HIGH", "Legacy TLS protocol accepted",
   "a network attacker decrypts traffic with known protocol attacks",
   "nginx: ssl_protocols TLSv1.2 TLSv1.3; (use https://ssl-config.mozilla.org profile)"),
 "tls-expiry": ("A04", "MEDIUM", "TLS certificate expiring soon",
   "browsers reject the site, HTTPS breaks, HSTS pins the outage",
   "automate renewal: certbot or ACME client with reload hook, alert when <21 days remain"),
 "tls-unverified": ("A04", "MEDIUM", "TLS certificate not trusted or mismatched",
   "users see warnings and MITM becomes trivial",
   "install a certificate from a trusted CA covering this exact hostname, keep the chain complete"),
 "hdr-hsts": ("A02", "HIGH", "Strict-Transport-Security missing",
   "first visit can be stripped to HTTP, enabling session theft",
   "add_header Strict-Transport-Security \"max-age=63072000; includeSubDomains; preload\" always;"),
 "hdr-csp-missing": ("A02", "MEDIUM", "Content-Security-Policy missing",
   "injected scripts run freely, XSS impact jumps from leak to takeover",
   "start report-only: Content-Security-Policy-Report-Only: default-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; report-uri /csp-report, then enforce"),
 "hdr-csp-unsafe": ("A05", "MEDIUM", "CSP allows unsafe-inline or unsafe-eval",
   "the policy stops almost no injected script",
   "drop unsafe-inline/unsafe-eval from script-src, use per-response nonces with 'strict-dynamic'"),
 "hdr-nosniff": ("A02", "MEDIUM", "X-Content-Type-Options missing",
   "browsers MIME-sniff responses into executable content",
   "add_header X-Content-Type-Options \"nosniff\" always;"),
 "hdr-referrer": ("A02", "LOW", "Referrer-Policy missing",
   "full URLs (with tokens in query strings) leak to third parties",
   "add_header Referrer-Policy \"strict-origin-when-cross-origin\" always;"),
 "hdr-permissions": ("A02", "LOW", "Permissions-Policy missing",
   "scripts can reach camera, microphone, geolocation without consent gating",
   "add_header Permissions-Policy \"geolocation=(), camera=(), microphone=()\" always;"),
 "hdr-xss-legacy": ("A02", "LOW", "X-XSS-Protection set to an unsafe value",
   "the legacy browser filter itself can create XSS on otherwise safe pages",
   "set X-XSS-Protection: 0 or remove the header entirely, rely on CSP"),
 "hdr-obsolete": ("A02", "LOW", "Obsolete pinning/CT header present",
   "Expect-CT/HPKP are dead standards and add noise or breakage",
   "remove Expect-CT and Public-Key-Pins headers; rely on CT logs and CAA records"),
 "hdr-coop": ("A02", "INFO", "Cross-Origin-Opener-Policy missing",
   "cross-origin documents can share a browsing context (Spectre-class risk)",
   "add_header Cross-Origin-Opener-Policy \"same-origin\" always;"),
 "hdr-corp": ("A02", "INFO", "Cross-Origin-Resource-Policy missing",
   "responses can be read cross-origin in no-cors contexts",
   "add_header Cross-Origin-Resource-Policy \"same-site\" always; (test PDFs first)"),
 "hdr-x-powered": ("A02", "LOW", "Framework fingerprint header present",
   "attackers match your exact framework/version to known exploits",
   "suppress it: nginx proxy_hide_header X-Powered-By;, or framework config expose_php=Off / X-Powered-By off"),
 "hdr-banner": ("A03", "LOW", "Server version disclosed in banner",
   "version-matched exploits (CVE lookups) become one-shot",
   "nginx: server_tokens off;, or proxy_hide_header Server; then set a generic Server value at the edge"),
 "hdr-cache-sensitive": ("A02", "MEDIUM", "Sensitive page is cacheable",
   "shared caches and browsers persist authenticated pages",
   "add_header Cache-Control \"no-store, private\" always; on login/account/API responses"),
 "clickjack": ("A02", "MEDIUM", "Page can be framed (clickjacking)",
   "an invisible overlay on a trusted page hijacks clicks and inputs",
   "add_header X-Frame-Options \"DENY\" always; and CSP frame-ancestors 'none'"),
 "cors-reflect": ("A01", "MEDIUM", "CORS reflects arbitrary Origin",
   "any website can read this origin's responses with the victim's cookies",
   "allowlist exact origins server-side, never echo the request Origin; keep Access-Control-Allow-Credentials off unless required"),
 "cors-null": ("A01", "MEDIUM", "CORS trusts the null origin",
   "sandboxed iframes and local files replay as trusted origin",
   "reject Origin: null explicitly, allowlist only your real origins"),
 "cors-star": ("A02", "INFO", "Wildcard CORS on an authenticated endpoint",
   "if credentials are ever added, the pairing is invalid and dangerous",
   "use explicit origins instead of * wherever credentials or private data are involved"),
 "cookie-secure": ("A07", "MEDIUM", "Session cookie without Secure flag",
   "the cookie travels over plain HTTP and can be stolen in transit",
   "Set-Cookie attributes: Secure; HttpOnly; SameSite=Lax"),
 "cookie-httponly": ("A07", "MEDIUM", "Session cookie without HttpOnly",
   "any XSS payload reads document.cookie and exfiltrates the session",
   "add HttpOnly to all session cookies"),
 "cookie-samesite": ("A07", "LOW", "Session cookie without SameSite",
   "cross-site requests carry the session, widening CSRF",
   "add SameSite=Lax (or Strict for state-changing flows)"),
 "cookie-plaintext": ("A04", "HIGH", "Session cookie issued over HTTP",
   "session identifiers are readable and replayable on the wire",
   "serve the site over HTTPS only and set Secure on every session cookie"),
 "cookie-long-life": ("A07", "LOW", "Session cookie lives for a very long time",
   "stolen cookies stay valid for months",
   "use short idle timeout (15-30 min) plus absolute expiry, rotate the ID on login"),
